package hristovski.nikola.generic_store.api_gateway.application;

import hristovski.nikola.generic_store.api_gateway.spring.ApiGatewayConfiguration;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.annotation.Import;

// Excluding UserDetailsServiceAutoConfiguration
// because we dont want the autogenerated password to be shown in the logs
@SpringBootApplication(exclude = {UserDetailsServiceAutoConfiguration.class})
//@EnableEurekaClient
@EnableDiscoveryClient
@EnableZuulProxy
@Slf4j
@Import({ApiGatewayConfiguration.class})
public class ApiGatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(ApiGatewayApplication.class, args);
    }

//    //TODO CHECK IF ITS WORKING WITH THIS COMMENTED OUT
//    @Bean
//    public WebMvcConfigurer corsConfigurer() {
//        log.info("Inside cors configurer");
//        return new WebMvcConfigurer() {
//            public void addCorsMappings(CorsRegistry registry) {
//                registry.addMapping("/**")
//                        .allowedOrigins("*")
//                        .allowedMethods("GET", "POST", "PUT", "DELETE");
//            }
//        };
//    }

}
